scenario_name: "toy_scenario_001"

seed: 0

space:
  width: 100.0
  height: 100.0
  range: 40.0    # 通信可能距離

sim:
  max_steps: 500
  time_step: 1.0    # シミュレーションの時間ステップ

command_center:
  position: [50.0, 50.0]

repair_depot:
  position: [50.0, 50.0]
  repair_duration: 10   # 修理に要するステップ数

failure_model:
  module: acta.sim.failure_models
  class: WeibullFailureModel
  params:
    lambd: 0.01   # 故障率 λ
    k: 1.5        # 形状パラメータ k

# task_selection:
#   module: acta.sim.task_selection
#   class: NearestIncompleteTaskSelector
#   params: {}

task_selection:
  module: acta.sim.task_selection
  class: GABasedTaskSelector
  params:
    interval: 500
    pop_size: 10
    generations: 1000
    elitism_rate: 0.1
    seed: 123
    L_max: 5
    seed: 1234

workers_csv: "toy_workers.csv"
tasks_csv:   "toy_tasks.csv"
